name       : wlroots
version    : 0.8.1
release    : 1
source     :
    - https://github.com/swaywm/wlroots/releases/download/0.8.1/wlroots-0.8.1.tar.gz : 202b86e0e21699b6660bbda56afc2e3358db7252f83ff69c89f01926b4900d98
license    : MIT
component  : desktop.library
summary    : A modular Wayland compositor library
description: |
    Pluggable, composable, unopinionated modules for building a Wayland compositor
builddeps  :
    - pkgconfig(freerdp2)
    - pkgconfig(gl)
    - pkgconfig(libavcodec)
    - pkgconfig(libinput)
    - pkgconfig(libpng)
    - pkgconfig(pixman-1)
    - pkgconfig(wayland-egl)
    - pkgconfig(wayland-protocols)
    - pkgconfig(x11)
    - pkgconfig(xkbcommon)
    - pkgconfig(xcb-icccm)
setup      : |
    %meson_configure -Dx11-backend=enabled
build      : |
    %ninja_build
install    : |
    %ninja_install
