name       : wlroots
version    : 0.10.1
release    : 2
source     :
    - https://github.com/swaywm/wlroots/archive/0.10.1.tar.gz : b84baefbaff7bb04b3d2c43cbacef1a433e2cd65111f8fbf4bfc5faaa4b34b08
license    : MIT
component  : desktop.library
summary    : A modular Wayland compositor library
description: |
    Pluggable, composable, unopinionated modules for building a Wayland compositor
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libavcodec)
    - pkgconfig(libinput)
    - pkgconfig(libpng)
    - pkgconfig(pixman-1)
    - pkgconfig(wayland-egl)
    - pkgconfig(wayland-protocols)
    - pkgconfig(x11)
    - pkgconfig(xkbcommon)
    - pkgconfig(xcb-icccm)
setup      : |
    %meson_configure -Dx11-backend=enabled
build      : |
    %ninja_build
install    : |
    %ninja_install
