name       : wlroots
version    : 1.13.0
release    : 5
source     :
    - https://github.com/swaywm/wlroots/releases/download/0.13.0/wlroots-0.13.0.tar.gz : f6bea37fd4a6f5e5f552b83d61adae8c73e64b0bcb9ae0ab464ebcd9309d3cf3
license    : MIT
component  : desktop.library
homepage   : https://github.com/swaywm/wlroots
summary    : A modular Wayland compositor library
description: |
    Pluggable, composable, unopinionated modules for building a Wayland compositor
builddeps  :
    - pkgconfig(gbm)
    - pkgconfig(libavcodec)
    - pkgconfig(libdrm)
    - pkgconfig(libinput)
    - pkgconfig(libpng)
    - pkgconfig(pixman-1)
    - pkgconfig(wayland-egl)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xfixes)
    - pkgconfig(xkbcommon)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-renderutil)
    - pkgconfig(xorg-server)
setup      : |
    %meson_configure -Dx11-backend=enabled -Dxwayland=enabled
build      : |
    %ninja_build
install    : |
    %ninja_install
