name       : wlroots
version    : 0.15.1
release    : 8
source     :
    - https://gitlab.freedesktop.org/wlroots/wlroots/-/archive/0.15.1/wlroots-0.15.1.tar.gz : 5b92f11a52d978919ed1306e0d54c9d59f1762b28d44f0a2da3ef3b351305373
license    : MIT
component  : desktop.library
homepage   : https://github.com/swaywm/wlroots
summary    : A modular Wayland compositor library
description: |
    Pluggable, composable, unopinionated modules for building a Wayland compositor
builddeps  :
    - pkgconfig(gbm)
    - pkgconfig(libavcodec)
    - pkgconfig(libdrm)
    - pkgconfig(libinput)
    - pkgconfig(libpng)
    - pkgconfig(libseat)
    - pkgconfig(pixman-1)
    - pkgconfig(wayland-egl)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xfixes)
    - pkgconfig(xkbcommon)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-renderutil)
    - pkgconfig(xorg-server)
setup      : |
    %meson_configure -Dbackends=auto -Dxwayland=auto
build      : |
    %ninja_build
install    : |
    %ninja_install
